blank_issues_enabled: false
contact_links:
  - name: Request a new Feature or Enhancement to package.
    # This annoying url is used so it can pre-fill some parts of the new discussion that needs to be created.
    # Follow the link to see what will be displayed.
    url: https://github.com/chocolatey-community/chocolatey-packages/discussions/new?category=ideas
    about: Open a discussion to request a feature or enhancement be implemented for a specific package.
  - name: Request a new package being migrated to this repository.
    # This same annoying url is used here as well to pre-fill some parts of the new discussion that needs to be created.
    # Follow the link to see what will be displayed.
    url: https://github.com/chocolatey-community/chocolatey-packages/discussions/new?category=migrations
    about: Open a discussion about moving a package you own, or have permission to move over to this repository.
  - name: Ask a Question
    url: https://github.com/chocolatey-community/chocolatey-packages/discussions/categories/q-a
    about: Do you have a question about a specific package, or maybe the repository itself?
